using System.Globalization;
using System.Net;
using System.Text;

namespace Dispatch.Application.Reporting;

/// <summary>Shared building blocks for the self-contained HTML reports (runner, load test, capture).</summary>
internal static class ReportHtml
{
    public static string E(string? s) => WebUtility.HtmlEncode(s ?? "");

    public static string N(double value, string format = "0") => value.ToString(format, CultureInfo.InvariantCulture);

    public static StringBuilder Begin(string title, string heading, string? badge, bool? good)
    {
        var sb = new StringBuilder();
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">")
            .Append("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">")
            .Append($"<title>{E(title)}</title><style>{Styles}</style></head><body>")
            .Append($"<h1>{E(heading)}");
        if (badge is not null)
            sb.Append($" <span class=\"badge {(good switch { true => "passed", false => "failed", _ => "warn" })}\">{E(badge)}</span>");
        sb.Append("</h1>");
        return sb;
    }

    public static string End => "<footer class=\"muted\">Generated by Dispatch</footer></body></html>";

    /// <summary>A stat tile; <paramref name="bad"/> colours the value red (true), green (false) or not at all (null).</summary>
    public static string Stat(string label, string value, bool? bad = null, string? hint = null) =>
        $"<div class=\"stat\"><span class=\"muted\">{E(label)}</span><b{(bad is null ? "" : $" style=\"color:var(--{(bad.Value ? "bad" : "ok")})\"")}>{E(value)}</b>" +
        (hint is null ? "" : $"<small class=\"muted\">{E(hint)}</small>") + "</div>";

    /// <summary>A horizontal bar row for distributions.</summary>
    public static string Bar(string label, int count, int max, string? colour = null, string? suffix = null)
    {
        var width = max <= 0 ? 0 : Math.Max(count > 0 ? 1 : 0, 100.0 * count / max);
        return $"<div class=\"bar\"><span class=\"bl\">{E(label)}</span><span class=\"bt\"><i style=\"width:{N(width, "0.#")}%" +
               (colour is null ? "" : $";background:{colour}") + $"\"></i></span><span class=\"bv\">{count.ToString("N0", CultureInfo.InvariantCulture)}{E(suffix)}</span></div>";
    }

    public static string StatusColour(string status) => status.Length > 0 ? status[0] switch
    {
        '2' => "#16a34a",
        '3' => "#0284c7",
        '4' => "#d97706",
        '5' => "#dc2626",
        _ => "#6b7280"
    } : "#6b7280";

    public static string Bytes(long bytes) => bytes switch
    {
        < 1024 => $"{bytes} B",
        < 1024 * 1024 => $"{bytes / 1024.0:0.0} KB",
        < 1024L * 1024 * 1024 => $"{bytes / 1024.0 / 1024:0.0} MB",
        _ => $"{bytes / 1024.0 / 1024 / 1024:0.00} GB"
    };

    public const string Styles = """
        :root{--bg:#fff;--fg:#1d1f24;--muted:#6b7280;--card:#f6f7f9;--line:#e5e7eb;--ok:#16a34a;--bad:#dc2626;--warn:#d97706;--accent:#ff6c37}
        @media (prefers-color-scheme:dark){:root{--bg:#16181d;--fg:#e8eaed;--muted:#9aa0a6;--card:#1f2228;--line:#2d3139}}
        *{box-sizing:border-box}
        body{margin:0 auto;max-width:1200px;background:var(--bg);color:var(--fg);font:14px/1.5 system-ui,-apple-system,Segoe UI,sans-serif;padding:24px}
        h1{margin:0 0 4px;font-size:22px}h2{font-size:15px;margin:28px 0 10px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted)}
        .muted{color:var(--muted)}
        .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:20px 0}
        .stat{background:var(--card);border-radius:10px;padding:14px}.stat b{display:block;font-size:22px}.stat small{display:block}
        .badge{display:inline-block;padding:2px 10px;border-radius:999px;font-weight:600;font-size:12px;vertical-align:middle}
        .passed{background:#16a34a22;color:var(--ok)}.failed{background:#dc262622;color:var(--bad)}.warn{background:#d9770622;color:var(--warn)}
        .card{background:var(--card);border-radius:10px;padding:14px}
        .grid2{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:12px}
        table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--line)}
        th{color:var(--muted);font-weight:600;font-size:12px}td.r,th.r{text-align:right;font-variant-numeric:tabular-nums}
        .bar{display:grid;grid-template-columns:110px 1fr 70px;gap:8px;align-items:center;margin:4px 0;font-size:13px}
        .bt{background:var(--line);border-radius:4px;height:10px;overflow:hidden}.bt i{display:block;height:100%;background:var(--accent);border-radius:4px}
        .bv{text-align:right;font-variant-numeric:tabular-nums}
        .chart{display:flex;align-items:flex-end;gap:2px;height:140px;background:var(--card);border-radius:10px;padding:10px}
        .chart i{flex:1;min-width:2px;max-width:28px;background:var(--accent);border-radius:2px 2px 0 0}.chart i.e{background:var(--bad)}
        ul.ins{list-style:none;padding:0;margin:0}ul.ins li{padding:8px 12px;border-radius:8px;margin:6px 0;background:var(--card);border-left:4px solid var(--muted)}
        ul.ins li.good{border-color:var(--ok)}ul.ins li.warning{border-color:var(--warn)}ul.ins li.bad{border-color:var(--bad)}
        code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;word-break:break-all}
        .err{color:var(--bad);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;white-space:pre-wrap}
        footer{margin-top:32px;font-size:12px}
        """;
}
